version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
                region: AWS_DEFAULT_REGION
          context: aws-dev
          dockerfile: Dockerfile
          platform: linux/amd64
          push_image: true
          region: ${AWS_DEFAULT_REGION}
          repo: blist/api
          tag: "latest"
